name: DOCKER_BUILD

on:
  workflow_dispatch:
  
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build
        run: docker build -t test:3 \
            /folder
