name: echo

on:
  pull_request:
    branches:
      - echo_test
    types:
      - closed
  workflow_dispatch:


jobs:
  echo:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ECHO
        env:
          TEST: ${{ secrets.TEST1 }}
        run: |
          echo ${{ secrets.TEST1}}
          echo "${{ secrets.TEST1}}"
          echo $TEST
          echo "$TEST"
          # echo "is manual? : " ${{ github.event_name == 'workflow_dispatch' }}
          # echo "is pr? : " ${{ github.event_name == 'pull_request' }}
          # echo "is pr merge? : " ${{ github.event.pull_request.merged == true }}
          # echo "is pr and pr merge? : " ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
          # echo "is manual or (pr and pr merge)? : " ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
          # echo "branch from : " ${{ github.head_ref }}
          # echo "branch to : " ${{ github.base_ref }}
          # echo "branch from is main? : " ${{ github.head_ref == 'main' }}
          # echo "branch to is echo_test? : " ${{ github.base_ref == 'echo_test' }}
          # echo ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)) && github.base_ref == 'echo_test' }}
 
