name: echo

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  echo:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ECHO
        run: |
          echo ${{ github.event_name == 'workflow_dispatch' }}
          echo ${{ github.event_name == 'pull_request' }}
          echo ${{ github.event.pull_request.merged == true }}
          echo ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
          echo ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
          echo ${{ github.ref == 'refs/heads/main' }}
          echo ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}&& ${{ github.ref == 'refs/heads/main' }}
