name: AUTO_PR

on:
  workflow_dispatch:
  
jobs:
  change_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: PR TITLE
          body: PR BODY
          branch: new branch
          base: main
          token: ${{ secrets.PAT }}
