name: AUTO_PR_APPROVE_MERGE

on:
#   pull_request:
#     branches:
#       - main
#     types:
#       - closed
  workflow_dispatch:
  
jobs:
  change_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Change manifest
        run: |
          sed -ie "s/test-${GITHUB_REF##*/}:.*/test-${GITHUB_REF##*/}:${{ github.run_number }}/g" test.yaml
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add test.yaml
          git commit -m "update manifest to version:${{ github.run_number }}"
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update image version ${{ github.run_number }}
          title: Update manifest
          body: Update manifest
          branch: infra/mainfest
          base: main
          token: ${{ secrets.PAT }}
          
#       - name: Enable Pull Request Automerge
#         if: steps.cpr.outputs.pull-request-operation == 'created'
#         uses: peter-evans/enable-pull-request-automerge@v2
#         with:
#           token: ${{ secrets.PAT }}
#           pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
#           merge-method: squash    
      
      - name: Auto approve
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
