name: secret-example
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print secret
      env:
        DOCKER_USER: ${{ secrets.asd }}
      run: echo $DOCKER_USER
