- name: Setting application.yml
  uses: microsoft/variable-substitution@v1
  with:
    files: ./src/main/resources/application.yml
  env:
    sgis.key: ${{ secrets.SGIS_KEY }}
    sgis.secret: ${{ secrets.SGIS_SECRET }}
