name: slack_test

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  slack-test:
    if: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)) && github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo
        id: echo
        run: echo "HI"

      - name: CD notification to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,workflow,job
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : 'danger',
                title: 'Test',
                fields: [{
                  {
                    title: 'Result',
                    value: '${{ job.status }}' === 'success' ? 'Success' : 'Fail',
                    short: false
                  },
                  {
                    title: 'Repository',
                    value: '${process.env.AS_REPO}',
                    short: false
                  },
                  {
                    title: 'Action',
                    value: '${process.env.AS_WORKFLOW}',
                    short: false
                  }
                }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ (github.event_name == 'workflow_dispatch' && secrets.BACKEND_SLACK_WEBHOOK_URL) || (github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Web]') && secrets.FRONTEND_SLACK_WEBHOOK_URL) || secrets.BACKEND_SLACK_WEBHOOK_URL }}
        if: always()
