name: TEST_MODIFIED_FILE

on:
  workflow_dispatch:
  
jobs:
  change_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Modify file
        id: k8s_manifest_update
        working-directory: ${{ github.workspace }}
        run: |
          sed -ie "s/test-${GITHUB_REF##*/}:.*/test-${GITHUB_REF##*/}:${{ github.run_number }}/g" test.yaml
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add test.yaml
          git commit -m "update manifest to version:${{ github.run_number }}"
          git push -u origin ${GITHUB_REF##*/} '''
