name: TEST_MODIFIED_FILE

on:
  workflow_dispatch:
  
jobs:
  change_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Modify file
        id: k8s_manifest_update
        run: |
          bash "tree -a"
          bash "sed -ie 's/test_${GITHUB_REF##*/}:.*/test_${GITHUB_REF##*/}:${{ github.run_number }}/g' test.yaml"
          bash '''
              git add test.yaml
              git commit -m "update manifest to version:${{ github.run_number }}"
              git push -u origin ${GITHUB_REF##*/} '''
